name: tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Unit Tests
        run: ./unit-tests.sh
      - name: Integration Tests
        run: docker-compose up --abort-on-container-exit --exit-code-from integration-tests